### ISSUE TITLE
fr: yeux

### ISSUE THREAD

**Issue by elijahsimkin** [open-dict-data/ipa-dict#47]
Missing IPA:
jø

**Comment by dohliam** [comment]
@elijahsimkin Do you perhaps have an old version of the project repo? The entry for _yeux_ has been included in the `fr_FR` dictionary since [this commit](https://github.com/open-dict-data/ipa-dict/commit/fd2dae1d9fc7fa0994ceed63549625a88cc3606e#diff-b66b807efd26c75db38bc668b071f510ad7665a03ff2009beb38adc1bc1750a7R245263) in 2018.
