### ISSUE TITLE
fr: seule

### ISSUE THREAD

**Issue by elijahsimkin** [open-dict-data/ipa-dict#48]
feminine seul
sœl

**Comment by dohliam** [comment]
@elijahsimkin Are you sure that you are looking at the current version of `fr_FR.txt`? The entry _seule_ is already included there and has been [since 2018](https://github.com/open-dict-data/ipa-dict/commit/fd2dae1d9fc7fa0994ceed63549625a88cc3606e#diff-b66b807efd26c75db38bc668b071f510ad7665a03ff2009beb38adc1bc1750a7R216265).
